name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag aiogram/telegram-bot-api:$(date +%Y%m%d) --tag aiogram/telegram-bot-api:latest
      - name: Publish Docker Image
        # You may pin to the exact commit or the version.
        # uses: tinact/docker.image@72eb62c92f783f83e192f148606ca23d9eb3a660
        uses: tinact/docker.image@1.0.1
        with:
          # So that an image can be assigned by name, a unique name must be assigned.
          image_name:
          # Each image should have a tag for unique identification.
          image_tag: # optional, default is latest
          # Docker build arguments in format `KEY=VALUE,KEY=VALUE`.
          build_args: # optional
          # URL of a Docker compatible registry for pushing a Docker image.
          registry: # optional, default is registry.hub.docker.com
          # Registry Username
          registry_username:
          # Registry Password. This should be stored in a Secret on Github.

      See https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables.

          registry_password:
          # Storage location of the Docker file.
          dockerfile: # optional, default is dockerfile