name: Docker Image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v2
      - &checkout-upstream
        name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
          submodules: recursive
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
      - &setup-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - &setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - &login-dockerhub
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - &set-version
        name: Set version
        id: current-version
        run: |
          TG_SERVER_VERSION=$(cat telegram-bot-api/CMakeLists.txt | grep TelegramBotApi | cut -d " " -f3)
          echo "TG_SERVER_VERSION=${TG_SERVER_VERSION}" >> $GITHUB_ENV
          echo "Parsed version: ${TG_SERVER_VERSION}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with: &build-and-push-with
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            aiogram/telegram-bot-api:latest
            aiogram/telegram-bot-api:${{ env.TG_SERVER_VERSION }}

  build-arm:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *checkout-upstream
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-arm-${{ github.sha }}
      - *setup-qemu
      - *setup-buildx
      - *login-dockerhub
      - *set-version
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          <<: *build-and-push-with
          platforms: linux/arm/v7,linux/arm64
          tags: |
            aiogram/telegram-bot-api:arm-${{ env.TG_SERVER_VERSION }}
